//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarsztaWeb.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Uslugi
    {
        public int id_Uslugi { get; set; }
        public string Opis_Usterek { get; set; }
        public int id_Samochodu { get; set; }
        public int id_Pracownika { get; set; }
        public string Status { get; set; }

        [JsonIgnore]
        public  Pracownicy Pracownicy { get; set; }
        [JsonIgnore]
        public Samochody Samochody { get; set; }
        [JsonIgnore]
        public  Wydruk Wydruk { get; set; }
    }
}
