//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarsztatWS.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Wydruk
    {
        public int id_Wydruku { get; set; }
        public string Opis { get; set; }
        public double Cena_uslugi { get; set; }

        [JsonIgnore]
        public Uslugi Uslugi { get; set; }
    }
}
